# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20171224_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='categories',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
